require('lars-vc/impatient')
require('lars-vc/telescope')
require('lars-vc/whichkey')
require('lars-vc/web-devicons')
require('lars-vc/treesitter')
require('lars-vc/lightspeed')
require('lars-vc/indentguides')
require('lars-vc/notify')
-- require('lars-vc/presence')
require('lars-vc/autopairs')
require('lars-vc/colorpicker')
require('lars-vc/lualine')
