require('lars-vc/telescope')
require('lars-vc/whichkey')
require('lars-vc/web-devicons')
require('lars-vc/treesitter')
require('lars-vc/lightspeed')
require('lars-vc/sniprun')
require('lars-vc/indentguides')
